metadata:
  favicon: ''
  title: Admin panel
  description: ''
  breakpoints: []
  rendererCachingEnabled: false
  skipDepsComparisonInCompilerCache: false
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
internalType: project
